# Generated by Django 4.0.3 on 2022-09-16 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('eventId', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Event ID')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Therapist')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', service.models.ChoiceArrayField(base_field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=10), blank=True, default=list, help_text='List of integers [1, 3]', size=10)),
                ('start_time', models.TimeField(help_text='10:00', verbose_name='Start time')),
                ('end_time', models.TimeField(help_text='10:00', verbose_name='End time')),
                ('valid_from', models.DateField(help_text='2022-09-15', verbose_name='Valid from')),
                ('valid_to', models.DateField(help_text='2022-10-15', verbose_name='Valid to')),
                ('force_create', models.BooleanField(default=False, verbose_name='Force create')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_therapist', to=settings.AUTH_USER_MODEL, verbose_name='Therapist')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ('therapist', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('eventId', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Event ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='service.slot', verbose_name='Slot')),
            ],
            options={
                'verbose_name': 'Massage',
                'verbose_name_plural': 'Massages',
                'ordering': ('start_time',),
            },
        ),
    ]
